DROP DATABASE IF EXISTS SIGDB;

CREATE DATABASE SIGDB;

USE SIGDB;

CREATE TABLE User(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    is_admin BOOLEAN default FALSE
);


CREATE TABLE SIG(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) NOT NULL,
    User INTEGER NOT NULL,
    FOREIGN KEY (User) REFERENCES User(ID) ON DELETE CASCADE
);


CREATE TABLE Couche(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) NOT NULL,
    SIG INTEGER NOT NULL,
    FOREIGN KEY (SIG) REFERENCES SIG(ID) ON DELETE CASCADE
);



CREATE TABLE Polygone (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) ,
    IDCouche INTEGER NOT NULL,
    FOREIGN KEY (IDCouche) REFERENCES Couche(ID) ON DELETE CASCADE

);

CREATE TABLE PointAbs (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    X INTEGER NOT NULL,
    Y INTEGER NOT NULL,
    IDPolygone INTEGER DEFAULT NULL,
    FOREIGN KEY (IDPolygone) REFERENCES Polygone(ID) ON DELETE CASCADE
);

CREATE TABLE Point(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) ,
    IDPointAbs INTEGER NOT NULL,
    IDCouche INTEGER NOT NULL,
    FOREIGN KEY (IDPointAbs) REFERENCES PointAbs(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDCouche) REFERENCES Couche(ID) ON DELETE CASCADE
);

CREATE TABLE Ligne (
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) ,
    A INTEGER NOT NULL,
    B INTEGER NOT NULL,
    IDCouche INTEGER NOT NULL,
    FOREIGN KEY (A) REFERENCES PointAbs(ID) ON DELETE CASCADE,
    FOREIGN KEY (B) REFERENCES PointAbs(ID) ON DELETE CASCADE,
    FOREIGN KEY (IDCouche) REFERENCES Couche(ID) ON DELETE CASCADE

);


CREATE TABLE TableAttr(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) ,
    IDCouche INTEGER NOT NULL,
    FOREIGN KEY (IDCouche) REFERENCES Couche(ID) ON DELETE CASCADE
);


CREATE TABLE Colonne(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) ,
    IDTableAttr INTEGER NOT NULL,
    FOREIGN KEY (IDTableAttr) REFERENCES TableAttr(ID) ON DELETE CASCADE
);


CREATE TABLE Symbologie(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) ,
    IDCouche INTEGER NOT NULL,
    FOREIGN KEY (IDCouche) REFERENCES Couche(ID) ON DELETE CASCADE
);

CREATE TABLE Couleur(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR(50) ,
    IDSymbologie INTEGER NOT NULL,
    FOREIGN KEY (IDSymbologie) REFERENCES Symbologie(ID) ON DELETE CASCADE
);

CREATE TABLE Settings(
    ID INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,

);


INSERT INTO User VALUES (NULL, "root", "root", true );
INSERT INTO User VALUES (NULL, "admin", "admin", true );
INSERT INTO User VALUES (NULL, "chems", "chems", false );


INSERT INTO SIG VALUES (NULL, "SIG1", 1);
INSERT INTO SIG VALUES (NULL, "SIG2", 2);
INSERT INTO SIG VALUES (NULL, "SIG3", 1);
INSERT INTO SIG VALUES (NULL, "SIG4", 3);

INSERT INTO Couche VALUES (NULL, "Points1", 1);
INSERT INTO Couche VALUES (NULL, "Lignes1", 1);
INSERT INTO Couche VALUES (NULL, "Points2", 2);
INSERT INTO Couche VALUES (NULL, "Polygone3", 3);

INSERT INTO Polygone VALUES (NULL, "Polygone1", 4);
INSERT INTO Polygone VALUES (NULL, "Polygone2", 4);

INSERT INTO PointAbs VALUES (NULL, 1, 3, 1);
INSERT INTO PointAbs VALUES (NULL, 2, 3, 1);
INSERT INTO PointAbs VALUES (NULL, 3, 4, 1);
INSERT INTO PointAbs VALUES (NULL, -1, 4, 1);
INSERT INTO PointAbs VALUES (NULL, 1, 3, 2);
INSERT INTO PointAbs VALUES (NULL, 2, 3, 2);
INSERT INTO PointAbs VALUES (NULL, 3, 4, 2);
INSERT INTO PointAbs VALUES (NULL, 3, 3, null );
INSERT INTO PointAbs VALUES (NULL, -4, 4, null );
INSERT INTO PointAbs VALUES (NULL, 15, 20, null );
INSERT INTO PointAbs VALUES (NULL, -3, 60, null );
INSERT INTO PointAbs VALUES (NULL, 20, 1, null );
INSERT INTO PointAbs VALUES (NULL, 22, 5, null );
INSERT INTO PointAbs VALUES (NULL, 15, 20, null );
INSERT INTO PointAbs VALUES (NULL, -3, 60, null );
INSERT INTO PointAbs VALUES (NULL, 20, 1, null );
INSERT INTO PointAbs VALUES (NULL, 22, 5, null );

INSERT INTO Point VALUES (NULL, "point1", 8, 1);
INSERT INTO Point VALUES (NULL, "point1", 9, 1);
INSERT INTO Point VALUES (NULL, "point1", 10, 1);
INSERT INTO Point VALUES (NULL, "point1", 11, 3);
INSERT INTO Point VALUES (NULL, "point1", 12, 3);
INSERT INTO Point VALUES (NULL, "point1", 13, 3);

INSERT INTO Ligne VALUES (NULL, "ligne1", 14, 15, 2);
INSERT INTO Ligne VALUES (NULL, "ligne1", 16, 17, 2);

INSERT INTO TableAttr VALUES (NULL, "table1", 1);
INSERT INTO TableAttr VALUES (NULL, "table2", 2);
INSERT INTO TableAttr VALUES (NULL, "table3", 3);
INSERT INTO TableAttr VALUES (NULL, "table4", 4);

INSERT INTO Colonne VALUES (NULL, "ID", 1);
INSERT INTO Colonne VALUES (NULL, "ID", 2);
INSERT INTO Colonne VALUES (NULL, "ID", 3);
INSERT INTO Colonne VALUES (NULL, "ID", 4);

INSERT INTO Symbologie VALUES (NULL, "symbole1", 1);
INSERT INTO Symbologie VALUES (NULL, "symbole2", 2);
INSERT INTO Symbologie VALUES (NULL, "symbole3", 3);
INSERT INTO Symbologie VALUES (NULL, "symbole4", 4);

INSERT INTO Couleur VALUES (NULL, "color1", 2);
INSERT INTO Couleur VALUES (NULL, "color2", 3);
